### ISSUE TITLE
fiche technique 

### ISSUE THREAD

**Issue by nabilqasmi** [hemoespoir-io/backend#2]
Une fiche technique conçue pour mieux identifier le patient utilise plusieurs variables d'entrée telles que l'âge, le poids, le groupe sanguin, le type de maladie, et les médicaments à administrer en cas d'urgence. Cette fonctionnalité est essentielle car elle peut sauver la vie de l'individu en permettant une intervention rapide et adaptée à sa condition spécifique.

Cette version améliorée offre une meilleure structure et clarté, en mettant l'accent sur l'importance de la fiche technique pour le traitement d'urgence.

**Comment by qasmi** [comment]
nom
age
poid
type de maladie
group sanguine 
numero de contact 
numero d'urgence
nom de médecine
liste medicament:
  type de medicament 
  dose 
  date de prise

**Comment by nabilqasmi** [comment]
la fiche technique déjà faite voici le test Curl : curl -X GET "http://localhost:5000/fichemedical?patientid=9"
